### ISSUE TITLE
Model weights

### ISSUE THREAD

**Issue by yagcaglar** [DanielMengLiu/DeepLip#1]
Hi, thank you for your work. Could you provide the model weights of the trained model that obtained the results in the paper?

**Comment by DanielMengLiu** [comment]
Hi, I tried to find the model. It's a pity I can't locate the exact model anymore since this work was finished three years ago. However, I find models with very similar performance; you could download them via google drive.
https://drive.google.com/drive/folders/1IalsNtmDH-qFnfgmn_O92J1MUHCaQepl?usp=sharing

I sincerely suggest you use the new version AudioVisualLip which is accepted by ICASSP2023 (https://arxiv.org/pdf/2302.11254.pdf, code: https://github.com/DanielMengLiu/AudioVisualLip) which I changed the x-vector to EcapaTDNN and modified the MCNN as well. We also provide the preprocessing code which you could use to extract your own lip ROIs (https://github.com/DanielMengLiu/AudioVisualLip/tree/main/preprocess).
